### ISSUE TITLE
Demo can not reachable.

### ISSUE THREAD

**Issue by seijiro** [gothinkster/react-mobx-realworld-example-app#1]
[Demo](https://react-mobx.realworld.io/) can't access.

**Comment by SandeeshS** [comment]
@seijiro the demo hasn't been setup yet. For now you can install the project locally and test it.

**Comment by hodorswit** [comment]
@seijiro sorry for about that, the demo should be up and running now at the following URL: 

https://gothinkster.github.io/react-mobx-realworld-example-app

I've also updated the README to reflect the new demo location.

**Comment by dennistang** [comment]
Demo is inaccessible again!

**Comment by andykog** [comment]
@dennistang, fixed (#4)
