### ISSUE TITLE
Profile page doesn't show your avatar in top banner

### ISSUE THREAD

**Issue by Engineering-Robert** [gothinkster/react-mobx-realworld-example-app#19]
![image](https://user-images.githubusercontent.com/16786990/31512819-3ebf9312-af5a-11e7-9902-ceb6a00b7f97.png)

It would be neat to have your avatar show up on the profile page.

**Comment by andykog** [comment]
@Engineering-Robert, seems that you haven't chosen any image at your profile page. https://react-mobx.realworld.io/#/settings otherwise it should work fine. Please reopen if it doesn't.
