### ISSUE TITLE
Why is there a "#" in the home URL route?

### ISSUE THREAD

**Issue by Engineering-Robert** [gothinkster/react-mobx-realworld-example-app#20]
https://react-mobx.realworld.io/#/

Why isn't it just https://react-mobx.realworld.io/ ? It seems like a more elegant solution instead of having an unnecessary "#"? Just curious as to the reasoning.

**Comment by andykog** [comment]
@Engineering-Robert, because the app uses [hash router](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md) as far as the backend is not configred for using history api
