### ISSUE TITLE
Sass files

### ISSUE THREAD

**Issue by kuangthien** [gothinkster/react-mobx-realworld-example-app#24]
Hello author,

Could you pls tell me how to use sass with this starter kit?
I saw your main.css from the CDN but idk how to setup sass/images folder for my proj :dancer: 
thanks in advance ;)

**Comment by andykog** [comment]
Hello @kuangthien,
This is not a sterter kit, but rather a demo app. You could use webpack loaders: [sass-loader](https://webpack.js.org/loaders/sass-loader/) & [file-loader](https://webpack.js.org/loaders/file-loader/)/[url-loader](https://webpack.js.org/loaders/url-loader/) to import those files directly into modules, or just serve static assets from “public” folder (the configuration depends on the back end you are using).
Overall, your question is out of scope of this project.
