### ISSUE TITLE
Promise.resolve()

### ISSUE THREAD

**Issue by IvanDimanov** [gothinkster/react-mobx-realworld-example-app#25]
Can we use
`Promise.resolve()`

from
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

instead of
`new Promise(res => res())`

from here
https://github.com/gothinkster/react-mobx-realworld-example-app/blob/6092ac392d32eb5be77f669c630bc21d94e69581/src/stores/authStore.js#L63

**Comment by andykog** [comment]
Thanks for noticing, fixed!
