### ISSUE TITLE
Upgrade to react-router 4?

### ISSUE THREAD

**Issue by bluepeter** [gothinkster/react-mobx-realworld-example-app#9]
Are there any plans to upgrade this to react-router 4? It's markedly different, and seems like it would be a good evolution for this project.

**Comment by bluepeter** [comment]
I have an almost complete branch with react-router 4 working. It surprisingly results in a lot less code. Will hopefully PR tomorrow.

**Comment by andykog** [comment]
@bluepeter, nice! Looking forward
